c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Controllers/MovieController.cs
using App.DataAccess;
using App.Web.Areas.Samples.Model;
using App.Web.Models;
using App.Web.Services.Contracts;
using App.Web.Utilities;
using System.Web.Mvc;

namespace App.Web.Areas.Samples.Controllers
{
    [AppAuth]
    [Module(Name = AppActions.Samples_masterdata)]
    public class MovieController : BaseCrudController<IMovieServices, MovieViewModel, Movie, MovieForm>
    {
        public override ActionResult Index() {
            return base.Index();
        }

        public override ActionResult Entry(string id, string opt) {
            return base.Entry(id, opt);
        }

        [HttpPost]
        [Log("Input Movie")]
        public override ActionResult Entry(MovieViewModel vm) {
            var result = base.EntryAction(vm);
            SetActivityLogData(result.ViewModel?.Form?.Name);

            if(ModelState.IsValid)
                return result.Action.Success("Meninput Movie "+ result.ViewModel.Form?.Name);
            else
                return result.Action;
        }

        [HttpPost]
        [Log("Delete Movie")]
        public override ActionResult Delete(string id) {
            var result = base.DeleteAction(id);
            SetActivityLogData(result.ViewModel?.Form?.Name);
            return result.Action.Success("Menghapus Movie "+ result.ViewModel?.Form?.Name);
        }

        [HttpPost]
        public override ActionResult GetList(DttRequestForm form) {
            return base.GetList(form);
        }

        protected override MovieViewModel ViewModelLoader(MovieViewModel vm) {
            vm = base.ViewModelLoader(vm);

            vm.Categories = Service.GetCategories();

            return vm;
        }

    }
}

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Movie/Entry.cshtml
@model App.Web.Areas.Samples.Model.MovieViewModel
@{
    ViewBag.Title = "Entry";
}

@Html.Partial("_ValidationMessage")
<div class="m-portlet">

    @using (Html.BeginForm("Entry", "Movie", new { area = "Samples" }, FormMethod.Post, new { id = "all", @class = "m-form" })) {
        <div class="m-portlet__body">
            <div class="m-form__section m-form__section--first" data-title="">
                @Html.AntiForgeryToken()
                <input type="hidden" name="@Html.NameFor(t => t.Form.Id)" value="@(Model.Form?.Id)" />

                @Html.FormFieldPartial((Model.Form?.Name ?? "").ToString(), new TextFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Name).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Name).ToString(),
                    HelpText = "",
                    Placeholder = "Name",
                    CssClass = "",
                    Style = TextFieldStyle.Simple
                })

                @Html.FormFieldPartial((Model.Form?.Category ?? "").ToString(), new SelectFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Category).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Category).ToString(),
                    HelpText = "",
                    Placeholder = "Category",
                    CssClass = "",
                    AddEmptyOption = true,
                    EmptyOptionLabel = "--Pilih--",
                    Options = Model.Categories,
                    OptionValueGetter = t => t.ToString(),
                    OptionLabelGetter = t => t.ToString()
                })

                @Html.FormFieldPartial((Model.Form?.Language ?? "").ToString(), new RadioFieldSetting() {
                   InputName = Html.NameFor(t => t.Form.Language).ToString(),
                   Label = Html.LabelForRequired(e => e.Form.Language).ToString(),
                   HelpText = "",
                   Placeholder = "Language",
                   CssClass = "",
                   Options = new List<string>() { "ID","EN" },
                   OptionValueGetter = t => t.DirectCastTo<string>(),
                   OptionLabelGetter = t => t.DirectCastTo<string>()
                })

                @Html.FormFieldPartial((Model.Form?.ReleaseDate), new DateTimeFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.ReleaseDate).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.ReleaseDate).ToString(),
                    HelpText = "",
                    Placeholder = "Name",
                    Style = DateTimeFieldStyle.DateOnly
                })

                @Html.FormFieldPartial(Model.Form?.Rating, new IntFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Rating).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Rating).ToString(),
                    HelpText = "",
                    Placeholder = "Rating",
                    CssClass = ""
                })

            </div>


        </div>
        <div class="m-portlet__foot m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions">
                <button type="submit" name="@Html.NameFor(t => t.Form.IsDraft).ToString()" value="true" class="btn btn-secondary">Save as Draft</button>
                <button type="submit" name="@Html.NameFor(t => t.Form.IsDraft).ToString()" value="false" class="btn btn-primary btnsave">Save</button>
            </div>
        </div>
    }

</div>

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Movie";
    var controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    var areaname = ViewContext.RouteData.DataTokens["area"];
}



<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text"></h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="/@areaname/@controllerName/entry" class="btn btn-focus m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                        <span>
                            <i class="fa fa-plus"></i>
                            <span>Add New</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>

    </div>
    <div class="m-portlet__body">

        @Html.Partial("~/Views/Shared/Metronic/_TableToolsDynamic.cshtml")
        <table class="table table-striped table-bordered table-hover table-checkable" id="datatable">
            <thead>
                <tr>
                    @(Html.RenderColumnsHtml(typeof(MovieForm)))
                </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                <tr>
                    @(Html.RenderColumnsHtml(typeof(MovieForm)))
                </tr>
            </tfoot>
        </table>
    </div>
</div>


@section scripts{
    @*<style>
            #override.fordynamic {
                display: none;
            }
        </style>*@

    <script>
        var dtListing = {};
        var ds = [];

        var columns = @(Html.RenderColumnsOption(typeof(MovieForm)));

        $(document).ready(function () {
            DatatableInit($('#datatable'), { columnDefs: columns, url: '/@areaname/@controllerName/GetList', useNumberCol:true})
        });
        function deleteListing() {
            if (!confirm("Apakah Anda yakin menghapus data ini ?")) {
                return false;
            }
        }

        function languageRender(data, type, row) {

            var icon = data === 'ID' ? 'indonesia.svg' : 'united-kingdom.svg';

            return `<div>
                    ${data}<img src="/assets/app/media/img/${icon}" height="15rem" style="margin-left:1rem;"/>
                </div>`
        }
    </script>

}