c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Controllers/TicketController.cs
using App.DataAccess;
using App.Web.Areas.Samples.Model;
using App.Web.Services.Contracts;
using App.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.Web.Areas.Samples.Controllers
{
    [Module(Name = AppModule.Samples_Ticket)]
    public class TicketController : BaseController<ITicketServices, TicketViewModel>
    {
        IMasterDataServices _masterDataSvc;
        public TicketController(IMasterDataServices masterDataSvc) : base() {
            _masterDataSvc = masterDataSvc;
        }

        public ActionResult Index() {
            return View(ViewModelLoader());
        }

        [HttpPost]
        [Log("Order Ticket")]
        [ValidateAntiForgeryToken]
        public ActionResult Index(TicketViewModel vm) {

            vm = ViewModelLoader(vm);

            if (!ModelState.IsValid) {
                return View(vm);
            }

            if (Service.IsSameDataExists<Ticket,TicketForm>(vm.Form)) {
                ModelState.AddDuplicateErrorState();
                return View(vm);
            }

            var result = Service.Insert(vm.Form);
            SetActivityLogData(result?.ShowTimeId);
            return RedirectToAction("Invoice",new { id = result.Id }).Success("Melakukan order");

        }

        [HttpGet]
        public ActionResult Invoice(string id) {
            SetBreadCrumbs(new BreadCrumbItem("/Samples/Ticket", "Order Ticket"),
                new BreadCrumbItem("/Samples/Ticket/Invoice/" + id, "Invoice"));
            return View(new TicketViewModel() { Form = Service.GetTicketById(id) });

        }


        //Ajax Sample
        [HttpPost]
        public ActionResult CheckCoupon(string id) {

            return Json(Service.CheckCoupon(id));
        }

        [HttpPost]
        public ActionResult ShowtimeDetail(string id) {

            return Json(Service.GetShowtimeDetail(id));
        }

        protected override TicketViewModel ViewModelLoader(TicketViewModel vm = null) {
            vm = base.ViewModelLoader(vm);

            vm.ShowTimes = _masterDataSvc.GetAll<ShowTime, ShowTimeForm>(false, "Movie", "Theatre");
            vm.PaymentMethods = Service.GetPaymentMethods();

            return vm;
        }

        public ActionResult GetInvoice(string id) {

            if (id == null) return Redirect(Request.UrlReferrer.ToString()).Error("Invoice Tidak Ditemukan");

            var result = Service.GetInvoice(id);

            if (result?.Bytes == null) return Redirect(Request.UrlReferrer?.ToString()??"/").Error("Invoice Tidak Ditemukan");

            return File(Service.GetInvoice(id));
        }
    }
}

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Ticket/Index.cshtml
@model App.Web.Areas.Samples.Model.TicketViewModel


@{
    ViewBag.Title = "Order Ticket";
}


@Html.Partial("_ValidationMessage")
<div class="m-portlet">

    @using (Html.BeginForm("Index", "Ticket", new { area = "Samples" }, FormMethod.Post, new { id = "all", @class = "m-form" })) {
        <div class="m-portlet__body">
            <div class="m-form__section m-form__section--first" data-title="">
                @Html.AntiForgeryToken()
                <input type="hidden" name="@Html.NameFor(t => t.Form.Id)" value="@(Model.Form?.Id)" />

                @Html.FormFieldPartial(Model.Form?.ShowTimeId, new SelectFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.ShowTimeId).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.ShowTimeId).ToString(),
                    HelpText = "",
                    Placeholder = "Show Time",
                    CssClass = "",
                    AddEmptyOption = true,
                    EmptyOptionLabel = "--Pilih--",
                    Options = Model.ShowTimes,
                    OptionLabelGetter = t => t.DirectCastTo<ShowTimeForm>().ToString(),
                    OptionValueGetter = t => t.DirectCastTo<ShowTimeForm>().Id,
                    HtmlId = "showtime"
                })


                @Html.FormFieldPartial(Model.Form?.SeatNumber, new TextFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.SeatNumber).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.SeatNumber).ToString(),
                    HelpText = "",
                    Placeholder = "Seat Number",
                    Style = TextFieldStyle.Simple
                })

                @Html.FormFieldPartial(Model.Form?.PaymentMethod, new SelectFieldSetting() {
                     InputName = Html.NameFor(t => t.Form.PaymentMethod).ToString(),
                     Label = Html.LabelForRequired(e => e.Form.PaymentMethod).ToString(),
                     HelpText = "",
                     Placeholder = "Payment Method",
                     CssClass = "",
                     AddEmptyOption = true,
                     EmptyOptionLabel = "--Pilih--",
                     Options = Model.PaymentMethods,
                     OptionLabelGetter = t => t.ToString(),
                     OptionValueGetter = t => t.ToString()
                 })


                @Html.FormFieldPartial(Model.Form?.OriginalPrice, new DecimalFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.OriginalPrice).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.OriginalPrice).ToString(),
                    HelpText = "",
                    Placeholder = "Original Price",
                    HtmlId = "oriprice",
                    Disabled = true
                })

                @Html.FormFieldPartial(Model.Form?.PromoCode, new TextFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.PromoCode).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.PromoCode).ToString(),
                    HelpText = "",
                    Placeholder = "Promo Code",
                    HtmlId = "promocode",
                    Style = TextFieldStyle.Simple
                })

                @Html.FormFieldPartial(Model.Form?.Discount, new DecimalFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Discount).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Discount).ToString(),
                    HelpText = "",
                    Placeholder = "Discount",
                    HtmlId = "discount",
                    Disabled = true
                })


                @Html.FormFieldPartial(Model.Form?.Price, new DecimalFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Price).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Price).ToString(),
                    HelpText = "",
                    Placeholder = "Price",
                    HtmlId = "price",
                    Disabled = true
                })


            </div>


        </div>
        <div class="m-portlet__foot m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions">
                <button type="submit" class="btn btn-primary btnsave">Save</button>
            </div>
        </div>
    }

</div>


@section scripts{
    <script>

        var currShowtime = {};
        var currCoupon = {};
        var lastcode = '';

        $('#showtime select').change(function () {
            var value = $('#showtime select').val();

            ajaxCall('/samples/ticket/ShowtimeDetail/' + value, null, function (result) {

                currShowtime = result || {};

                $('#oriprice input[type=text]').numberVal(result.Price);
                $('#oriprice input[type=text]').trigger('change');

                calculateDiscount();

            })

        })

        

        $('#showtime select').change(function () {
            var value = $('#showtime select').val();

            ajaxCall('/samples/ticket/ShowtimeDetail/' + value, null, function (result) {

                currShowtime = result || {};

                $('#oriprice input[type=text]').numberVal(result.Price);
                $('#oriprice input[type=text]').trigger('change');

                calculateDiscount();

            })

        })

        $('#promocode input').keyup(function () {
            var value = $(this).val();
            $('#promocode .m-form__help').html('');
            if (value) {

                $('#promocode .m-form__help').html('Checking...');

                delay(function (e) {
                    ajaxCall('/samples/ticket/CheckCoupon/' + value, null, function (result) {
                        
                    console.log(result);
                        if (result) {

                            currShowtime = result || {};

                            $('#discount input[type=text]').numberVal(result.Potongan);
                            $('#discount input[type=text]').trigger('change');
                            $('#promocode .m-form__help').html('Valid...');

                            currCoupon = result;

                        } else {
                            currCoupon = {};
                            $('#discount input[type=text]').numberVal(0);
                            $('#discount input[type=text]').trigger('change');
                            $('#promocode .m-form__help').html('Invalid...');
                        }

                        calculateDiscount();

                    })
                }, 1000)
            }
        });

        function calculateDiscount() {
            
            var oriprice = $('#oriprice input[type=hidden]').val() || 0;
            var discount = $('#discount input[type=hidden]').val() || 0;
            var price = parseFloat(oriprice) - parseFloat(discount);

            $('#price input[type=text]').numberVal(price);
            $('#price input[type=text]').trigger('change');

        }
    </script>

}

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Ticket/Invoice.cshtml
@model App.Web.Areas.Samples.Model.TicketViewModel
@{
    ViewBag.Title = "Invoice";
    var controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    var areaname = ViewContext.RouteData.DataTokens["area"];
}

@section styles{
    <style>
        #invoice {
            padding: 30px;
        }

        .invoice {
            position: relative;
            background-color: #FFF;
            min-height: 680px;
            padding: 15px
        }

            .invoice header {
                padding: 10px 0;
                margin-bottom: 20px;
                border-bottom: 1px solid #3989c6
            }

            .invoice .company-details {
                text-align: right
            }

                .invoice .company-details .name {
                    margin-top: 0;
                    margin-bottom: 0
                }

            .invoice .contacts {
                margin-bottom: 20px
            }

            .invoice .invoice-to {
                text-align: left
            }

                .invoice .invoice-to .to {
                    margin-top: 0;
                    margin-bottom: 0
                }

            .invoice .invoice-details {
                text-align: right
            }

                .invoice .invoice-details .invoice-id {
                    margin-top: 0;
                    color: #3989c6
                }

            .invoice main {
                padding-bottom: 50px
            }

                .invoice main .thanks {
                    margin-top: -100px;
                    font-size: 2em;
                    margin-bottom: 50px
                }

                .invoice main .notices {
                    padding-left: 6px;
                    border-left: 6px solid #3989c6
                }

                    .invoice main .notices .notice {
                        font-size: 1.2em
                    }

            .invoice table {
                width: 100%;
                border-collapse: collapse;
                border-spacing: 0;
                margin-bottom: 20px
            }

                .invoice table td, .invoice table th {
                    padding: 15px;
                    background: #eee;
                    border-bottom: 1px solid #fff
                }

                .invoice table th {
                    white-space: nowrap;
                    font-weight: 400;
                    font-size: 16px
                }

                .invoice table td h3 {
                    margin: 0;
                    font-weight: 400;
                    color: #3989c6;
                    font-size: 1.2em
                }

                .invoice table .qty, .invoice table .total, .invoice table .unit {
                    text-align: right;
                    font-size: 1.2em
                }

                .invoice table .no {
                    color: #fff;
                    font-size: 1.6em;
                    background: #3989c6
                }

                .invoice table .unit {
                    background: #ddd
                }

                .invoice table .total {
                    background: #3989c6;
                    color: #fff
                }

                .invoice table tbody tr:last-child td {
                    border: none
                }

                .invoice table tfoot td {
                    background: 0 0;
                    border-bottom: none;
                    white-space: nowrap;
                    text-align: right;
                    padding: 10px 20px;
                    font-size: 1.2em;
                    border-top: 1px solid #aaa
                }

                .invoice table tfoot tr:first-child td {
                    border-top: none
                }

                .invoice table tfoot tr:last-child td {
                    color: #3989c6;
                    font-size: 1.4em;
                    border-top: 1px solid #3989c6
                }

                .invoice table tfoot tr td:first-child {
                    border: none
                }

            .invoice footer {
                width: 100%;
                text-align: center;
                color: #777;
                border-top: 1px solid #aaa;
                padding: 8px 0
            }

        @@media print {
            .invoice {
                font-size: 11px !important;
                overflow: hidden !important
            }

                .invoice footer {
                    position: absolute;
                    bottom: 10px;
                    page-break-after: always
                }

                .invoice > div:last-child {
                    page-break-before: always
                }
        }
    </style>
}

<div id="invoice">

    <div class="toolbar hidden-print">
        <div class="text-right">
            <a class="btn btn-info" href="/@areaname/@controllerName/GetInvoice/@(Model.Form?.Id)"><i class="fa fa-file-word"></i> Export</a>
        </div>
        <hr>
    </div>
    <div class="invoice overflow-auto">
        <div style="min-width: 600px">
            <main>
                <div class="row contacts">
                    <div class="col invoice-to">
                    </div>
                    <div class="col invoice-details">
                        <h1 class="invoice-id">INVOICE @(Model?.Form?.CreatedDate.ToString("yyyyMMddHHmm"))</h1>
                        <div class="date">Date of Invoice: @(Model?.Form?.CreatedDate.ToString("dd MMM yyyy"))</div>
                        <div class="date">Due Date: @(Model?.Form?.CreatedDate.AddMinutes(90).ToString("dd MMM yyyy HH:mm"))</div>
                    </div>
                </div>
                <table border="0" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th class="text-left">DESCRIPTION</th>
                            <th class="text-right">SEAT</th>
                            <th class="text-right">PRICE</th>
                            <th class="text-right">TOTAL</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="no">01</td>
                            <td class="text-left"><h3>@ShowTimeForm.GetDescFromModel(Model.Form?.ShowTime)</h3></td>
                            <td class="unit">@(Model.Form?.SeatNumber)</td>
                            <td class="qty">@(Model.Form?.OriginalPrice?.ToFormatedString(addRupiah: true))</td>
                            <td class="total">@(Model.Form?.OriginalPrice?.ToFormatedString(addRupiah: true))</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2">SUBTOTAL</td>
                            <td>@(Model.Form?.OriginalPrice?.ToFormatedString(addRupiah: true))</td>
                        </tr>
                        @if (!string.IsNullOrEmpty(Model.Form?.PromoCode)) {
                            <tr>
                                <td colspan="2"></td>
                                <td colspan="2">PROMO (@(Model.Form?.PromoCode))</td>
                                <td>-@(Model.Form?.Discount?.ToFormatedString(addRupiah: true))</td>
                            </tr>
                        }
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2">GRAND TOTAL</td>
                            <td>Rp@(Model.Form?.Price?.ToFormatedString())</td>
                        </tr>
                    </tfoot>
                </table>
                <div class="thanks">Thank you!</div>
                <div class="notices">
                    <div>NOTICE:</div>
                    <div class="notice">Please finish the payment before <strong>@(Model.Form?.CreatedDate.AddMinutes(90).ToString("dd MMM yyyy HH:mm"))</strong></div>
                </div>
            </main>
            <footer>
                Invoice was created on a computer and is valid without the signature and seal.
            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
        <div></div>
    </div>
</div>