c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Controllers/TheatreController.cs
using App.DataAccess;
using App.Web.Areas.Samples.Model;
using App.Web.Services.Contracts;
using App.Web.Utilities;

namespace App.Web.Areas.Samples.Controllers
{
    [AppAuth]
    [Module(Name = AppModule.Samples_MasterData)]
    public class TheatreController : BaseCrudController<ITheatreServices, TheatreViewModel, Theatre, TheatreForm>
    {
        
    }
}

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Theatre/Entry.cshtml
@model App.Web.Areas.Samples.Model.TheatreViewModel
@{
    ViewBag.Title = "Entry";
}

@Html.Partial("_ValidationMessage")
<div class="m-portlet">

    @using (Html.BeginForm("Entry", "Theatre", new { area = "Samples" }, FormMethod.Post, new { id = "all", @class = "m-form" })) {
        <div class="m-portlet__body">
            <div class="m-form__section m-form__section--first" data-title="">
                @Html.AntiForgeryToken()
                <input type="hidden" name="@Html.NameFor(t => t.Form.Id)" value="@(Model.Form?.Id)" />

                @Html.FormFieldPartial((Model.Form?.Name ?? "").ToString(), new TextFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.Name).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.Name).ToString(),
                    HelpText = "",
                    Placeholder = "Name",
                    CssClass = "",
                    Style = TextFieldStyle.Simple
                })


                @Html.FormFieldPartial(Model.Form?.NumberOfSeat, new IntFieldSetting() {
                    InputName = Html.NameFor(t => t.Form.NumberOfSeat).ToString(),
                    Label = Html.LabelForRequired(e => e.Form.NumberOfSeat).ToString(),
                    HelpText = "",
                    Placeholder = "Number Of Seat",
                    CssClass = ""
                })

            </div>


        </div>
        <div class="m-portlet__foot m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions">
                <button type="submit" name="@Html.NameFor(t => t.Form.IsDraft).ToString()" value="true" class="btn btn-secondary">Save as Draft</button>
                <button type="submit" name="@Html.NameFor(t => t.Form.IsDraft).ToString()" value="false" class="btn btn-primary btnsave">Save</button>
            </div>
        </div>
    }

</div>

c-sharp-starter-pack-master/c-sharp-starter-pack-master/Boilerplate/App/App.Web/Areas/Samples/Views/Theatre/Index.cshtml
@{
    ViewBag.Title = "Theatre";
    var controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    var areaname = ViewContext.RouteData.DataTokens["area"];
}



<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text"></h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="/@areaname/@controllerName/entry" class="btn btn-focus m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                        <span>
                            <i class="fa fa-plus"></i>
                            <span>Add New</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>

    </div>
    <div class="m-portlet__body">

        @Html.Partial("~/Views/Shared/Metronic/_TableToolsDynamic.cshtml")
        <table class="table table-striped table-bordered table-hover table-checkable" id="datatable">
            <thead>
                <tr>
                    @(Html.RenderColumnsHtml(typeof(TheatreForm)))
                </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                <tr>
                    @(Html.RenderColumnsHtml(typeof(TheatreForm)))
                </tr>
            </tfoot>
        </table>
    </div>
</div>


@section scripts{
    @*<style>
            #override.fordynamic {
                display: none;
            }
        </style>*@

    <script>
        var dtListing = {};
        var ds = [];

        var columns = @(Html.RenderColumnsOption(typeof(TheatreForm)));

        $(document).ready(function () {
            DatatableInit($('#datatable'), { columnDefs: columns, url: '/@areaname/@controllerName/GetList', useNumberCol:true})
        });
    </script>

}